DamageAction =     require './damageAction'
_ = require 'underscore'

###
  Hurting damage actions are generated by the hurting phase of the game when a player has no more cards in the deck.
###
class HurtingDamageAction extends DamageAction

  @type:"HurtingDamageAction"

  damageAmount: 2

  constructor: () ->
    @type ?= HurtingDamageAction.type
    super

module.exports = HurtingDamageAction
